apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          {{ if .Values.volumes }}
          volumeMounts:
            {{- range .Values.volumes }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
            {{- end }}
          {{ end }}
          {{ if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{ end }}
          {{ if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{ if .Values.volumes }}
      volumes:
        {{- range .Values.volumes }}
          - name: {{ .name }}
            persistentVolumeClaim:
              claimName: {{ .claim }}
        {{- end }}
      {{ end }}