name: portal-noticias

replicaCount: 3

image:
  repository: aluracursos/portal-noticias
  tag: "1"

service:
  type: NodePort
  port: 80
  nodePort: 30000

resources:
  requests:
    cpu: 10m

data:
  IP_SISTEMA: http://localhost:30001

volumes: {}

livenessProbe:
  httpGet:
    path: /
    port: 80

readinessProbe:
  httpGet:
    path: /
    port: 80